//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Search_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public int Combo_ID { get; set; }
        public string Combo_Name { get; set; }
        public System.DateTime Combo_Date { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual User User { get; set; }
    }
}
