//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Search_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Dishes_Contain_Food
    {
        public int Dishes_ID { get; set; }
        public int Food_ID { get; set; }
        public int DCF_ID { get; set; }

        public string DishesContainFoodName { get; set; }
        public string Count { get; set; }

    
        public virtual Dishes Dishes { get; set; }
        public virtual Food Food { get; set; }
    }
}
