//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Search_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dishes()
        {
            this.Combo = new HashSet<Combo>();
        }
    
        public int Dishes_ID { get; set; }
        public string Dishes_Name { get; set; }
        public string Dishes_Methods { get; set; }
        public byte[] Dishes_Photo { get; set; }
        public string Dishes_Remark { get; set; }
        public System.DateTime Dishes_Recommend_Date { get; set; }
        public Nullable<System.DateTime> Food_Review_Date { get; set; }
        public byte Food_Review_Result { get; set; }
        public string Referral_User_ID { get; set; }
        public string Review_Manager_ID { get; set; }
    
        public virtual Dishes_Contain_Food Dishes_Contain_Food { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combo> Combo { get; set; }
        public virtual User User1 { get; set; }
    }
}
