//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Search_Proj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Food_searchEntities : DbContext
    {
        public Food_searchEntities()
            : base("name=Food_searchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories_Of_Food> Categories_Of_Food { get; set; }
        public virtual DbSet<Combo> Combo { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Dishes_Contain_Food> Dishes_Contain_Food { get; set; }
        public virtual DbSet<Feedback_Article> Feedback_Article { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Set_Menu_Includes_Dishes> Set_Menu_Includes_Dishes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Collect_Combo> User_Collect_Combo { get; set; }
        public virtual DbSet<User_Collect_Dishes> User_Collect_Dishes { get; set; }
    }
}
