//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Search_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Article
    {
        public int Article_ID { get; set; }
        public string Article_Title { get; set; }
        public string Article_Text { get; set; }
        public System.DateTime Article_Date { get; set; }
        public byte Article_Review_Result { get; set; }
        public string Article_User_ID { get; set; }
        public string Article_Manager_ID { get; set; }
        public byte[] Article_Photo { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual User User { get; set; }
    }
}
