//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Search_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Dishes = new HashSet<Dishes>();
            this.Feedback_Article = new HashSet<Feedback_Article>();
            this.Combo = new HashSet<Combo>();
            this.Dishes1 = new HashSet<Dishes>();
        }

        [Required(ErrorMessage = "帳號不可空白")]
        [Display(Name = "帳號")]
        public string User_ID { get; set; }
        [Required(ErrorMessage = "密碼不可空白")]
        [Display(Name = "密碼")]
        public string User_Password { get; set; }
        [Display(Name = "確認密碼")]
        public string User_Password_Again { get; set; }
        [Required(ErrorMessage = "暱稱不可空白")]
        [Display(Name = "暱稱")]
        public string User_Nick_Name { get; set; }
        [Required(ErrorMessage = "Email不可空白")]
        [EmailAddress(ErrorMessage = "格式有誤！")]
        [Display(Name = "信箱")]
        public string User_Mail { get; set; }
        [Required(ErrorMessage = "手機號碼不可空白")]
        [StringLength(10, ErrorMessage = "電話格式錯誤！", MinimumLength = 10)]
        [Display(Name = "電話")]
        public string User_Phone { get; set; }
        [Display(Name = "生日")]
        public Nullable<System.DateTime> User_Birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dishes> Dishes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_Article> Feedback_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combo> Combo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dishes> Dishes1 { get; set; }
    }
}
